package business;

/**
 * TODO description
 */
public enum Channel {
	
	HOME,
	AIR_CONDITIONING_CONTROL,
	ALARM,
	AUTHENTICATION_DEVICE,
	AUTOMATED_AIR_CONDITIONING_CONTROL,
	AUTOMATED_AV,
	AUTOMATED_BLINDS,
	AUTOMATED_HEATING,
	AUTOMATED_ILLUMINATION,
	AUTOMATED_INHOUSE_ILLUMINATION,
	AUTOMATED_PERIMETER_ILLUMINATION,
	AUTOMATED_SPRINKLERS,
	AUTOMATED_VENTILATION_CONTROL,
	AUTOMATED_WINDOWS,
	AV_MANAGEMENT,
	AV_SIMULATION,
	BELL,
	BLINDS_MANAGEMENT,
	BLINDS_SIMULATION,
	CAMERAS,
	DES,
	ENCRYPTION_ALGORITHM,
	FINGERPRINT_READER,
	FIRE_CONTROL,
	FIRE_SPRINKLERS,
	FIRST_AID_GROUP,
	FULL_AUTOMATED_HVAC_CONTROL,
	FULL_MANUAL_HVAC_CONTROL,
	GLASSBREAK_SENSORS,
	HEATING_CONTROL,
	HVAC_MANAGEMENT,
	INTERNET,
	INTRUSION_DETECTION_DEVICE,
	IRRIGATION_SPRINKLERS,
	KEYPAD,
	LIGHT_MANAGEMENT,
	LIGHTS,
	LIGHT_SIMULATION,
	MANUAL_AIR_CONDITIONING_CONTROL,
	MANUAL_BLINDS,
	MANUAL_HEATING,
	MANUAL_ILLUMINATION,
	MANUAL_VENTILATION_CONTROL,
	MANUAL_WINDOWS,
	MOODS,
	OTHER_GROUP,
	PRESENCE_SIMULATION,
	PRIVACY,
	REMOTE_AIR_CONDITIONING_CONTROL,
	REMOTE_HEATING_CONTROL,
	RETINA_SCANNER,
	RSA,
	SECURITY,
	SIMPLE_CONTROL,
	SIREN,
	TOUCH_SCREEN,
	UI,
	VENTILATION_CONTROL,
	WINDOWS_MANAGEMENT,
	
	UNIDENTIFIED_CHANNEL;
	
	public static Channel parseChannel(String channelString) {
		Channel[] allChannels = Channel.values();
		for (Channel c : allChannels)
			if (c.toString().equals(channelString))
				return c;
		
		return UNIDENTIFIED_CHANNEL;
	}

}